package com.laserpay.pdei.simulator.world;

import com.laserpay.pdei.common.domain.EvidenceType;
import com.laserpay.pdei.common.hash.Hashes;
import com.laserpay.pdei.core.storage.Buckets;

import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * The bytes behind a generated piece of evidence.
 *
 * <p>Without these, "evidence" in a simulated world is a database row pointing at nothing, and
 * the two things PDEI actually claims to do - verify an artifact's hash, and search its text -
 * cannot be demonstrated at all. With them, {@code document-processor-service} has something
 * real to extract, {@code EvidenceIntegrityService} has something real to re-hash, and the
 * evidence explorer has something real to full-text search.
 *
 * <p>The content is plain text, deterministically rendered from the artifact's own fields, so
 * the same seed produces the same bytes and therefore the same sha256. Plain text rather than
 * generated PDFs on purpose: PDF writers embed timestamps and object ids that would break
 * byte-for-byte reproducibility, and the extraction path is already proven against real PDFs by
 * document-processor-service's own tests.
 *
 * @param evidenceId  the {@code EV-} id this artifact belongs to
 * @param merchantId  owning merchant
 * @param transactionId owning transaction
 * @param type        evidence type, which decides the document layout
 * @param filename    filename as it appears in the MinIO key and in a representment bundle
 * @param contentType MIME type
 * @param content     the bytes
 * @param sha256      hash of {@code content}
 */
public record SyntheticArtifact(String evidenceId,
                                String merchantId,
                                String transactionId,
                                EvidenceType type,
                                String filename,
                                String contentType,
                                byte[] content,
                                String sha256) {

    /**
     * Render a document for one piece of evidence.
     *
     * @param fields ordered field list that becomes the document body; use a
     *               {@link LinkedHashMap} so the rendering is deterministic
     */
    public static SyntheticArtifact render(String evidenceId, String merchantId, String transactionId,
                                           EvidenceType type, String title, Map<String, String> fields) {
        String body = renderBody(title, type, fields);
        byte[] content = body.getBytes(StandardCharsets.UTF_8);
        String filename = filenameFor(type, evidenceId);
        return new SyntheticArtifact(evidenceId, merchantId, transactionId, type, filename,
                "text/plain; charset=utf-8", content, Hashes.sha256(content));
    }

    /** Object key under {@code pdei-evidence}, per platform contract 11. */
    public String objectKey() {
        return Buckets.evidenceKey(merchantId, transactionId, type, evidenceId, 1, filename);
    }

    public int sizeBytes() {
        return content.length;
    }

    public String text() {
        return new String(content, StandardCharsets.UTF_8);
    }

    /**
     * A document laid out as a header block plus {@code key: value} lines. Boring by design: the
     * point is that it is searchable and hashable, not that it looks like a real invoice.
     */
    private static String renderBody(String title, EvidenceType type, Map<String, String> fields) {
        StringBuilder sb = new StringBuilder(256);
        sb.append(title).append('\n');
        sb.append("=".repeat(Math.min(80, title.length()))).append('\n');
        sb.append("Document type: ").append(type.name().replace('_', ' ')).append('\n');
        sb.append('\n');
        fields.forEach((key, value) -> {
            if (value != null && !value.isBlank()) {
                sb.append(key).append(": ").append(value).append('\n');
            }
        });
        sb.append('\n');
        sb.append("Generated by the PDEI simulator as synthetic evidence.\n");
        return sb.toString();
    }

    private static String filenameFor(EvidenceType type, String evidenceId) {
        String stem = switch (type) {
            case PAYMENT_PROOF -> "payment-proof";
            case INVOICE -> "invoice";
            case ORDER_RECORD -> "order-record";
            case SHIPPING_RECORD -> "shipping-record";
            case DELIVERY_PROOF -> "delivery-proof";
            case REFUND_RECEIPT -> "refund-receipt";
            case CUSTOMER_COMMUNICATION -> "customer-email";
            case MERCHANT_POLICY -> "merchant-policy";
            case TERMS_OF_SERVICE -> "terms-of-service";
            case AVS_CVV_RESULT -> "avs-cvv-result";
            case DEVICE_FINGERPRINT -> "device-fingerprint";
            case PRIOR_TRANSACTION_HISTORY -> "prior-transactions";
            case SIGNED_CONTRACT -> "signed-contract";
        };
        String suffix = evidenceId == null ? "artifact" : evidenceId.replace("EV-", "").toLowerCase(java.util.Locale.ROOT);
        return stem + "-" + suffix + ".txt";
    }
}
