-- =====================================================================================
-- V8__audit.sql  |  audit_events (hash-chained, append-only)
--
-- hash = sha256 over the canonical JSON of every field except `hash`
-- previous_hash = hash of the previous audit event IN THE SAME MERCHANT CHAIN
-- (Hashes.chain(previousHash, payloadHash) in platform-common).
--
-- GET /audit/verify-chain?merchantId= walks pdei.audit_events ordered by sequence_no and
-- reports the first divergence.
-- =====================================================================================

CREATE TABLE pdei.audit_events (
    audit_id      VARCHAR(64) NOT NULL,
    -- monotonic chain position, assigned by the database, never by the application
    sequence_no   BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    entity_type   VARCHAR(32) NOT NULL,
    entity_id     VARCHAR(64) NOT NULL,
    merchant_id   VARCHAR(64) NOT NULL,
    action        VARCHAR(64) NOT NULL,
    actor         VARCHAR(128) NOT NULL,
    actor_type    VARCHAR(32) NOT NULL,
    occurred_at   TIMESTAMPTZ NOT NULL,
    correlation_id VARCHAR(64),
    causation_id  VARCHAR(64),
    source_event_id VARCHAR(64),
    before_state  JSONB,
    after_state   JSONB,
    previous_hash VARCHAR(64),
    hash          VARCHAR(64) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_audit_events PRIMARY KEY (audit_id),
    CONSTRAINT uq_audit_events_hash UNIQUE (hash),
    CONSTRAINT ck_audit_events_id_prefix CHECK (audit_id LIKE 'AUD-%'),
    CONSTRAINT ck_audit_events_actor_type CHECK (actor_type IN (
        'SYSTEM', 'MERCHANT_USER', 'OPERATOR', 'AI_SERVICE', 'SIMULATOR')),
    CONSTRAINT ck_audit_events_entity_type CHECK (entity_type IN (
        'MERCHANT', 'CUSTOMER', 'TRANSACTION', 'PAYMENT', 'ORDER', 'SHIPMENT', 'DELIVERY',
        'REFUND', 'COMMUNICATION', 'EVIDENCE', 'POLICY', 'DISPUTE', 'CASE')),
    CONSTRAINT ck_audit_events_no_self_chain CHECK (previous_hash IS NULL OR previous_hash <> hash)
);

CREATE INDEX ix_audit_events_chain       ON pdei.audit_events (merchant_id, sequence_no);
CREATE INDEX ix_audit_events_entity      ON pdei.audit_events (entity_type, entity_id, occurred_at DESC);
CREATE INDEX ix_audit_events_occurred_at ON pdei.audit_events (occurred_at DESC);
CREATE INDEX ix_audit_events_actor       ON pdei.audit_events (actor);
CREATE INDEX ix_audit_events_correlation ON pdei.audit_events (correlation_id);
CREATE INDEX ix_audit_events_action      ON pdei.audit_events (merchant_id, action);

-- A merchant chain may fork neither at the head (one genesis) nor mid-chain (one
-- successor per link). Concurrent appenders therefore serialise on the chain, which is
-- exactly the intended semantics for a tamper-evident log.
CREATE UNIQUE INDEX ux_audit_events_genesis ON pdei.audit_events (merchant_id)
    WHERE previous_hash IS NULL;
CREATE UNIQUE INDEX ux_audit_events_link ON pdei.audit_events (merchant_id, previous_hash)
    WHERE previous_hash IS NOT NULL;

CREATE TRIGGER trg_audit_events_immutable
    BEFORE UPDATE OR DELETE ON pdei.audit_events
    FOR EACH ROW EXECUTE FUNCTION pdei.fn_reject_mutation();

COMMENT ON TABLE  pdei.audit_events               IS 'Append-only, hash-chained audit log. One chain per merchant, ordered by sequence_no.';
COMMENT ON COLUMN pdei.audit_events.hash          IS 'sha256 over canonical JSON of all fields except hash itself.';
COMMENT ON COLUMN pdei.audit_events.previous_hash IS 'hash of the preceding audit event for the same merchant, NULL for the chain genesis.';
